FROM python:3.8.1-buster

WORKDIR /app

COPY . /app

# installs dev dependencies with pipfile.lock and to the system's python
RUN pip install pipenv && \
    pipenv install --system --deploy --ignore-pipfile --dev
